### ISSUE TITLE
The Spanish version show this screen 

### ISSUE THREAD

**Issue by Monumilnides** [theheroGAC/Autoplugin#124]
Hi, I use my system in Spanish and when I start the app the following screen is displayed: 
https://i.ibb.co/N9XnRzN/20190115-173311-01.jpg
I have changed to English and it works correctly.

**Comment by theheroGAC** [comment]
fixed https://github.com/theheroGAC/Autoplugin/releases/download/3.69/Autoplugin.vpk

**Comment by Monumilnides** [comment]
The problem persists I will try to remove it completely and reinstalling

**Comment by Monumilnides** [comment]
It's still glitched, sorry.
